[profile.default]
src = "src"
out = "out"
libs = ["lib"]
remappings = [
    '@openzeppelin-contracts=lib/openzeppelin-contracts/contracts',
    '@openzeppelin-upgradeable=lib/openzeppelin-contracts-upgradeable/contracts',
    '@chainlink-local=lib/chainlink-local/lib',
    '@chainlink-brownie=lib/chainlink-brownie-contracts/contracts',
    '@AA=lib/account-abstraction/contracts',
    '@solmate=lib/solmate/src'
]
fs_permissions = [{access = "read-write", path = "./"}]
auto_detect_solc = true
# See more config options https://github.com/foundry-rs/foundry/blob/master/crates/config/README.md#all-options
